
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Aïkido');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Alpinisme');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Athlétisme');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Aviron');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Aérobic');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Apnée');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Aéromodélisme');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Badminton');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Balle au tambourin');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Bando');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Baseball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Base jump');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Basket-ball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Bateau-Dragon');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Biathlon');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Bicross');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Billard');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Bloc');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Bobsleigh');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Bowling');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Boxe');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','cirque');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Canoë-kayak');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Canyoning');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Course');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Course d''orientation');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Cricket');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Croquet');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Crosse');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Crossfit');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Curling');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Cyclisme');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Capoeira');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Cheerleading');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Conduite sur glace');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Catch');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','canoë');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','curling');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','cani-rando');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Danse');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Dames');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Deltaplane');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Décathlon');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Duathlon');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Double Dutch');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Équitation');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Escalade');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Escrime');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Échecs');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','équilibriste');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Floorball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Football');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Football américain');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Football australien');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Football gaélique');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Futsal');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Golf');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Gymnastique');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Gouren');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Glisse');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Hakko-Ryu');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Haltérophilie');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Handball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Hockey sur gazon');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Hockey sur glace');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Horse-ball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Hurling');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Iaïdo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Iaïjutsu');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Jeu de paume');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ju-Jitsu');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Joutes nautiques');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Judo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Javelot tir sur cible');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Jumping');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','java');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','jerk');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','jogging');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kaninhop');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Karaté');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','kathak');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kayak');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kick-boxing');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kitesurfing');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kronum');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Karting');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Keirin');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kendo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kempo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kin-ball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Kung fu');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Krav maga');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Lancer de disque');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Lancer de javelot');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Lancer de marteau');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Lancer de poids');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Luge de course');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Lutte');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Muay thaï');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Motocross');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Musculation');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Marathon');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','marche');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Naban');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Natation');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Natation synchronisée');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Nautisme');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Netball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Paddle');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Paintball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Parachutisme');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Parapente');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Parkour');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Patinage artistique');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Patinage de vitesse');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Pêche sportive');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Pelote basque');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Pentathlon moderne');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Pétanque');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Pilates');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ping-Pong');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Plongée');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Plumfoot');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Polo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Qi gong');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Quadrille');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Quad');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Quiddich');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Rafting');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Rallye automobile');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Régate');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ringuette');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Rink hockey');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Roller');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Roller in line hockey');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Rugby à sept');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Rugby à XIII');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Rugby à XV');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Roller Derby');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Savate');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Shinty');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Skateboard');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Skater hockey');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Skeleton');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ski alpin');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ski de fond');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ski nordique');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ski nautique');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Slamball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Snowboard');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Softball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Spéléologie');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Squash');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Sumo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Surf');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Supermotard');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Salsa');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','saut a ski');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Sport boule lyonnaise');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','sudoku sport cérébral');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Saut à la perche');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Saut en hauteur');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Saut en longueur');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Taekwondo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tambourin');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tae Bo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tai-chi-chuan');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Taihojutsu');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tchoukball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tennis');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tennis léger');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Twirling');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tennis de table');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tir');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tir à l''arc');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Triathlon');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Triple saut');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tango');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Tricking');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','ULM');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Ultimate');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Unihockey');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','ultra-trail');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Varappe');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Voile');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Volata');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Volley-ball');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','VTT');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Voltige');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Valse');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Wakeboard');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Water polo');
  insert into ACTIVITY (TYPE,NAME) values ('Sport','Wing Chun');
-- Leisure
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Plage');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Parc d''attraction');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Coder');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Cinéma');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Théâtre');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Concert');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Poterie');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Musée');
  insert into ACTIVITY (TYPE,NAME) values ('Leisure','Exposition');

-- good meteo exemple
  insert into ACTIVITY_METEO values (1,'nuit_claire'); 
  insert into ACTIVITY_METEO values (1,'couvert_avec_averses'); 

